credentials:
  users:
    replicator:
      password: 'topsecret'
      roles: [replication]
    client:
      password: 'secret'
      roles: [super]

iproto:
  listen: 'unix/:./{{ instance_name }}.iproto'
  advertise:
    peer: replicator@

log:
  to: file

replication:
  failover: election

groups:
  group-001:
    replicasets:
      replicaset-001:
        instances:
          instance-001: {}
          instance-002: {}
          instance-003: {}
