name: coverity

on:
  repository_dispatch:
    types: [backend_automation]
  workflow_dispatch:
  schedule:
    - cron:  '0 4 * * 6'

env:
  CI_MAKE: make -f .travis.mk

jobs:
  coverity:
    # We want to run on external PRs, but not on our own internal PRs
    # as they'll be run by the push to the branch.
    if: ( github.event_name == 'push' ||
        github.event.pull_request.head.repo.full_name != github.repository ) &&
        ! endsWith(github.ref, '-notest')

    runs-on: ubuntu-18.04

    strategy:
      fail-fast: false

    # Image built by .gitlab.mk instructions and targets from .travis.mk.
    # Also additional installation of coverity tool installation check
    # exists in target deps_coverity_debian at .travis.mk file.
    container:
      image: docker.io/tarantool/testing:debian-buster
      # Our testing expects that the init process (PID 1) will
      # reap orphan processes. At least the following test leans
      # on it: app-tap/gh-4983-tnt-e-assert-false-hangs.test.lua.
      options: '--init'

    steps:
      # Permissions correction is needed for self-host runners,
      # where work path is saved between different workflows runs.
      - name: correct permissions in working directory
        shell: bash
        run: |
          sudo chown -R $(id -u):$(id -g) .
      - uses: actions/checkout@v1
      - uses: ./.github/actions/environment
      - name: test
        run: ${CI_MAKE} test_coverity_debian_no_deps
        env:
          COVERITY_TOKEN: ${{ secrets.COVERITY_TOKEN }}
      - name: call action to send Telegram message on failure
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_CORE_TOKEN }}
          TELEGRAM_TO: ${{ secrets.TELEGRAM_CORE_TO }}
        uses: ./.github/actions/send-telegram-notify
        if: failure()
      - name: artifacts
        uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: debug
          retention-days: 21
          path: ${{ env.VARDIR }}/artifacts
      # Find the PR associated with this push, if there is one.
      - uses: jwalton/gh-find-current-pr@v1
        if: success()
        id: findPr
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Create comment in PR if it exists
        if: success() && steps.findPr.outputs.number != false
        uses: peter-evans/create-or-update-comment@v1
        with:
          issue-number: ${{ steps.findPr.outputs.pr }}
          body: |
            Check coverity results on coverity.com site
            [![Coverity Status](https://scan.coverity.com/projects/11609/badge.svg?flat=1)](https://scan.coverity.com/projects/tarantool-tarantool)
