name: coverity

on:
  workflow_dispatch:
  schedule:
    - cron:  '0 4 * * 6'

jobs:
  coverity:
    if: github.repository == 'tarantool/tarantool'

    runs-on: ubuntu-latest

    container:
      image: docker.io/tarantool/testing:debian-buster
      # Our testing expects that the init process (PID 1) will
      # reap orphan processes. At least the following test leans
      # on it: app-tap/gh-4983-tnt-e-assert-false-hangs.test.lua.
      options: '--init'

    steps:
      - name: Prepare checkout
        uses: tarantool/actions/prepare-checkout@ylobankov/improve-prepare-checkout
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          submodules: recursive
      - uses: ./.github/actions/environment
      - name: test
        run: make -f .test.mk test-coverity
        env:
          COVERITY_TOKEN: ${{ secrets.COVERITY_TOKEN }}
      - name: Send VK Teams message on failure
        if: failure()
        uses: ./.github/actions/report-job-status
        with:
          bot-token: ${{ secrets.VKTEAMS_BOT_TOKEN }}
      - name: artifacts
        uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: debug
          retention-days: 21
          path: ${{ env.VARDIR }}/artifacts
      # Find the PR associated with this push, if there is one.
      - uses: jwalton/gh-find-current-pr@v1
        if: success()
        id: findPr
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Create comment in PR if it exists
        if: success() && steps.findPr.outputs.number != false
        uses: peter-evans/create-or-update-comment@v1
        with:
          issue-number: ${{ steps.findPr.outputs.pr }}
          body: |
            Check coverity results on coverity.com site
            [![Coverity Status](https://scan.coverity.com/projects/11609/badge.svg?flat=1)](https://scan.coverity.com/projects/tarantool-tarantool)
