name: coverity

on:
  workflow_dispatch:
  schedule:
    - cron:  '0 4 * * 6'

env:
  CI_MAKE: make -f .travis.mk

jobs:
  coverity:
    if: github.repository == 'tarantool/tarantool'

    runs-on: ubuntu-18.04

    # Image built by .gitlab.mk instructions and targets from .travis.mk.
    # Also additional installation of coverity tool installation check
    # exists in target deps_coverity_debian at .travis.mk file.
    container:
      image: docker.io/tarantool/testing:debian-buster
      # Our testing expects that the init process (PID 1) will
      # reap orphan processes. At least the following test leans
      # on it: app-tap/gh-4983-tnt-e-assert-false-hangs.test.lua.
      options: '--init'

    steps:
      - uses: actions/checkout@v1
      - uses: ./.github/actions/environment
      - name: test
        run: ${CI_MAKE} test_coverity_debian_no_deps
        env:
          COVERITY_TOKEN: ${{ secrets.COVERITY_TOKEN }}
      - name: call action to send Telegram message on failure
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_CORE_TOKEN }}
          TELEGRAM_TO: ${{ secrets.TELEGRAM_CORE_TO }}
        uses: ./.github/actions/send-telegram-notify
        if: failure()
      - name: artifacts
        uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: debug
          retention-days: 21
          path: ${{ env.VARDIR }}/artifacts
      # Find the PR associated with this push, if there is one.
      - uses: jwalton/gh-find-current-pr@v1
        if: success()
        id: findPr
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Create comment in PR if it exists
        if: success() && steps.findPr.outputs.number != false
        uses: peter-evans/create-or-update-comment@v1
        with:
          issue-number: ${{ steps.findPr.outputs.pr }}
          body: |
            Check coverity results on coverity.com site
            [![Coverity Status](https://scan.coverity.com/projects/11609/badge.svg?flat=1)](https://scan.coverity.com/projects/tarantool-tarantool)
