name: debian_10_arm

on:
  push:
  pull_request:
  repository_dispatch:
    types: [backend_automation]
  workflow_dispatch:

jobs:
  debian_10_arm:
    # We want to run on external PRs, but not on our own internal PRs
    # as they'll be run by the push to the branch.
    if: ( github.event_name == 'push' ||
        github.event.pull_request.head.repo.full_name != github.repository ) &&
        ! endsWith(github.ref, '-notest')

    runs-on: odroid-arm64

    strategy:
      fail-fast: false

    steps:
      # Permissions correction is needed for self-host runners,
      # where work path is saved between different workflows runs.
      - name: correct permissions in working directory
        shell: bash
        run: |
          sudo chown -R $(id -u):$(id -g) .
      - uses: actions/checkout@v2.3.4
        with:
          fetch-depth: 0
          submodules: recursive
      - uses: ./.github/actions/environment
      - name: packaging
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_S3_ENDPOINT_URL: ${{ secrets.AWS_S3_ENDPOINT_URL }}
          LIVE_REPO_S3_DIR: ${{ secrets.LIVE_REPO_S3_DIR }}
          RELEASE_REPO_S3_DIR: ${{ secrets.RELEASE_REPO_S3_DIR }}
          GPG_SECRET_KEY: ${{ secrets.GPG_SECRET_KEY }}
          GPG_SIGN_KEY: ${{ secrets.GPG_SIGN_KEY }}
          OS: 'debian'
          DIST: 'buster'
        uses: ./.github/actions/pack_and_deploy
      - name: call action to send Telegram message on failure
        uses: ./.github/actions/typescript-telegram-notifier
        if: failure()
        with:
          token: ${{ secrets.TELEGRAM_CORE_TOKEN }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          chat_id: ${{ secrets.TELEGRAM_CORE_TO }}
          parse_mode: MarkdownV2
          disable_web_page_preview: true
      - name: artifacts
        uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: debian-buster
          retention-days: 21
          path: build/usr/src/*/tarantool-*/test/var/artifacts
