name: jepsen-cluster-txm

on:
  workflow_dispatch:

env:
  CI_MAKE: make -f .travis.mk

jobs:
  jepsen-cluster-txm:
    if: github.repository == 'tarantool/tarantool'

    runs-on: ubuntu-18.04

    # image built by .gitlab.mk instructions and targets from .travis.mk
    container:
      image: docker.io/tarantool/testing:debian-stretch
      ports:
        # Opens tcp port 2222 on the host for internal SSH port
        - 2222:22

    steps:
      - uses: actions/checkout@v1
      - name: long_test
        env:
          TF_VAR_keypair_name: ${{ secrets.TF_VAR_keypair_name }}
          TF_VAR_password: ${{ secrets.TF_VAR_password }}
          TF_VAR_tenant_id: ${{ secrets.TF_VAR_tenant_id }}
          TF_VAR_user_domain_id: ${{ secrets.TF_VAR_user_domain_id }}
          TF_VAR_user_name: ${{ secrets.TF_VAR_user_name }}
          TF_VAR_ssh_key: ${{ secrets.TF_VAR_ssh_key }}
          LEIN_OPT: '--nemesis standard --mvcc'
          INSTANCE_COUNT: '5'
        run: ${CI_MAKE} test_jepsen
      - name: call action to send Telegram message on failure
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_CORE_TOKEN }}
          TELEGRAM_TO: ${{ secrets.TELEGRAM_CORE_TO }}
        uses: ./.github/actions/send-telegram-notify
        if: failure()
      - name: artifacts
        uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: jepsen-cluster-txm
          retention-days: 21
          path: jepsen-tests-prefix/src/jepsen-tests/store
