name: jepsen-cluster

on:
  workflow_dispatch:

jobs:
  jepsen-cluster:
    if: github.repository == 'tarantool/tarantool'

    runs-on: ubuntu-latest

    container:
      image: docker.io/tarantool/testing:debian-buster
      ports:
        # Opens tcp port 2222 on the host for internal SSH port
        - 2222:22

    steps:
      - name: Prepare checkout
        uses: tarantool/actions/prepare-checkout@ylobankov/improve-prepare-checkout
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          submodules: recursive
      - name: Install deps
        uses: ./.github/actions/install-deps-jepsen
      - name: long_test
        env:
          TF_VAR_keypair_name: ${{ secrets.TF_VAR_keypair_name }}
          TF_VAR_password: ${{ secrets.TF_VAR_password }}
          TF_VAR_tenant_id: ${{ secrets.TF_VAR_tenant_id }}
          TF_VAR_user_domain_id: ${{ secrets.TF_VAR_user_domain_id }}
          TF_VAR_user_name: ${{ secrets.TF_VAR_user_name }}
          TF_VAR_ssh_key: ${{ secrets.TF_VAR_ssh_key }}
          LEIN_OPT: '--nemesis standard'
          INSTANCE_COUNT: '5'
        run: make -f .test.mk test-jepsen
      - name: Send VK Teams message on failure
        if: failure()
        uses: ./.github/actions/report-job-status
        with:
          bot-token: ${{ secrets.VKTEAMS_BOT_TOKEN }}
      - name: artifacts
        uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: jepsen-cluster
          retention-days: 21
          path: jepsen-tests-prefix/src/jepsen-tests/store
