name: jepsen-single-instance-txm

on:
  push:
    tags:
      - '*'
  repository_dispatch:
    types: [backend_automation]
  workflow_dispatch:
  schedule:
    - cron:  '0 */3 * * *'

env:
  CI_MAKE: make -f .travis.mk

jobs:
  jepsen-single-instance-txm:
    if: github.event_name == 'push' ||
        github.event_name == 'repository_dispatch' ||
        github.event_name == 'workflow_dispatch' ||
        github.event_name == 'schedule'

    runs-on: ubuntu-18.04

    strategy:
      fail-fast: false

    # image built by .gitlab.mk instructions and targets from .travis.mk
    container:
      image: docker.io/tarantool/testing:debian-stretch
      ports:
        # Opens tcp port 2222 on the host for internal SSH port
        - 2222:22

    steps:
      - uses: actions/checkout@v1
      - name: long_test
        env:
          TF_VAR_keypair_name: ${{ secrets.TF_VAR_keypair_name }}
          TF_VAR_password: ${{ secrets.TF_VAR_password }}
          TF_VAR_tenant_id: ${{ secrets.TF_VAR_tenant_id }}
          TF_VAR_user_domain_id: ${{ secrets.TF_VAR_user_domain_id }}
          TF_VAR_user_name: ${{ secrets.TF_VAR_user_name }}
          TF_VAR_ssh_key: ${{ secrets.TF_VAR_ssh_key }}
          LEIN_OPT: '--nemesis standard --mvcc'
        run: ${CI_MAKE} test_jepsen
      - name: call action to send Telegram message on failure
        uses: ./.github/actions/typescript-telegram-notifier
        if: failure()
        with:
          token: ${{ secrets.TELEGRAM_CORE_TOKEN }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          chat_id: ${{ secrets.TELEGRAM_CORE_TO }}
          parse_mode: MarkdownV2
          disable_web_page_preview: true
      - name: artifacts
        uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: jepsen-single-instance-txm
          retention-days: 21
          path: jepsen-tests-prefix/src/jepsen-tests/store
