name: lango-stale-reviews
on:
  schedule:
    - cron:  '0 */1 * * *'    # At every hour.
  workflow_dispatch:

jobs:
  update-last-activity-dates:
    env:
      LANGO_REVIEW_BOARD_TOKEN: ${{ secrets.LANGO_REVIEW_BOARD_TOKEN }}
      ORGANIZATION: Tarantool
      PROJECT_ID: 83
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python3
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: pip install requests
      - name: Update dates
        run: python tools/stale_pr_date_setter.py
