name: lint

on:
  push:
    branches-ignore:
      - '**-notest'
    tags:
      - '**'
  pull_request:
  repository_dispatch:
    types: [backend_automation]
  workflow_dispatch:

concurrency:
  # Update of a developer branch cancels the previously scheduled workflow
  # run for this branch. However, the 'master' branch, release branch (1.10,
  # 2.8, etc.), and tag workflow runs are never canceled.
  #
  # We use a trick here: define the concurrency group as 'workflow run ID' +
  # 'workflow run attempt' because it is a unique combination for any run.
  # So it effectively discards grouping.
  #
  # Important: we cannot use `github.sha` as a unique identifier because
  # pushing a tag may cancel a run that works on a branch push event.
  group: ${{ (
    github.ref == 'refs/heads/master' ||
    github.ref == 'refs/heads/1.10' ||
    startsWith(github.ref, 'refs/heads/2.') ||
    startsWith(github.ref, 'refs/tags/')) &&
    format('{0}-{1}', github.run_id, github.run_attempt) ||
    format('{0}-{1}', github.workflow, github.ref) }}
  cancel-in-progress: true

env:
  CI_MAKE: make -f .travis.mk

jobs:
  luacheck:
    # Run on pull request only if the 'notest' label is unset and this is
    # an external PR (internal PRs trigger a run on push).
    if: github.event_name != 'pull_request' ||
        ( ! contains(github.event.pull_request.labels.*.name, 'notest') &&
          github.event.pull_request.head.repo.full_name != github.repository )

    runs-on: ubuntu-20.04-self-hosted-test-terraform

    steps:
      - uses: actions/checkout@v2.3.4
        with:
          fetch-depth: 0
          submodules: recursive
      - name: test
        run: ${CI_MAKE} test_debian_luacheck
      - name: call action to send Telegram message on failure
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_CORE_TOKEN }}
          TELEGRAM_TO: ${{ secrets.TELEGRAM_CORE_TO }}
        uses: ./.github/actions/send-telegram-notify
        if: failure()

  release-notes:
    # Run on pull request only if the 'notest' label is unset and this is
    # an external PR (internal PRs trigger a run on push).
    if: github.event_name != 'pull_request' ||
        ( ! contains(github.event.pull_request.labels.*.name, 'notest') &&
          github.event.pull_request.head.repo.full_name != github.repository )

    runs-on: ubuntu-20.04-self-hosted-test-terraform

    steps:
      # We don't need neither deep fetch, nor submodules here.
      - uses: actions/checkout@v2.3.4
      # Don't use actions/setup-python to don't bother with proper
      # setup of our self-hosted machines, see [1].
      #
      # Any python version is okay for the script, even Python 2.
      #
      # [1]: https://github.com/actions/setup-python#using-setup-python-with-a-self-hosted-runner
      - run: ./tools/gen-release-notes
      - name: call action to send Telegram message on failure
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_CORE_TOKEN }}
          TELEGRAM_TO: ${{ secrets.TELEGRAM_CORE_TO }}
        uses: ./.github/actions/send-telegram-notify
        if: failure()
